graph TD
    classDef default white-space: nowrap

    A0["点击卡牌图片Image.onClick"] -.-> A1["handleCardClick(sourceIndex, cardIndex)"]
    A1 --> A2{"isLocked || cardsFlipped[cardIndex]"}
    -->|false| A3["clickCount++<br/>cardsFlipped[cardIndex] = true"]
    --> A4{"isNaN(justClicked)"}
    -->|true| A5["justClicked = cardIndex"]
    A4 -->|false| A6["isLocked = true"]
    --> A7{"sourceIndex === indexList[justClicked]"}
    -->|true| A8["flippedCount++<br/>justClicked = NaN<br/>isLocked = false"]
    --> A9{"flippedCount >= cardSources.length"}
    -->|true| A10["getUIContext().showAlertDialog 回合完成弹窗提示"]
    A7 -->|false| A11[setTimeout]
    -.-> A12["cardsFlipped[justClicked] = false<br/>cardsFlipped[cardIndex] = false<br/>justClicked = NaN<br/>isLocked = false"]

    A10 -.-> A13["primaryButton.action 再来一局"] --> B1

    B0[onPageShow] --> B1[resetGame]
    --> B2["indexList = initIndexList()<br/>cardsFlipped = indexList.map(() => false)<br/>justClicked = NaN<br/>flippedCount = 0<br/>startTime = Date.now()<br/>clickCount = 0<br/>isLocked = false"]